### ISSUE TITLE
Media cursor issue on RTL websites

### ISSUE THREAD

**Issue by HasanSibakhi** [Cuberto/mouse-follower#2]
When the website direction is from RTL
data-cursor-img
The cursor doesn't change to an image, Rather, the image comes next to the cursor, and the cursor remains the same as it.

✅I added the direction[LTR] to fix that -> css

.mf-cursor {
     direction: ltr;
}

Thanks ❣️

**Comment by Drafteed** [comment]
Hello! Fixed in [v1.0.3](https://github.com/Cuberto/mouse-follower/releases/tag/v1.0.3). Thank you!

**Comment by HasanSibakhi** [comment]
@Drafteed 
A special thank you with all my heart for your creativity. Super amazing works!

Let us be informed by such wonderful works 😉
