### ISSUE TITLE
MouseDrag on flickity carousel

### ISSUE THREAD

**Issue by Esmeth** [Cuberto/mouse-follower#20]
Any option to update the current cursor position on dragMouseMove with flickity carousel.

**Comment by Drafteed** [comment]
Hello! You should use option like `touchStartPreventDefault: false` in Swiper.

**Comment by Esmeth** [comment]
Hi @Drafteed thanks for your response, is there any same option for Flickity slider too ?

**Comment by Drafteed** [comment]
I don't use Flickity, you need to do some research.
