### ISSUE TITLE
Cursour saved on link relocate nextjs

### ISSUE THREAD

**Issue by rstp-god** [Cuberto/mouse-follower#23]
Hello! 
I have problem with links inside nextjs, when u click on Link with cursor, it wiil be save on new page that you relocate. 
Try to set hideOnLeave at manually set data-cursor-text="" still do not working

Here we click on link with cursor:
![image](https://user-images.githubusercontent.com/39411889/220101054-3109fb5f-1140-4c8e-b098-9f6bc03b8a6f.png)

Here how i set text on hover: 
![image](https://user-images.githubusercontent.com/39411889/220101383-d1e43576-93e5-49e9-a811-69f3eb4793bb.png)

Here new page with same cursour:
![image](https://user-images.githubusercontent.com/39411889/220101234-66e2e4d2-0d14-4100-bb94-9182d2d419fc.png)

mouse-follower version : 1.1.2
nextjs version : 13.0.5
react 18.2.0
gsap: 3.11.3

**Comment by Drafteed** [comment]
You need to use the onLeave hook (e.g. `routeChangeStart`) in Next.js and reset all cursor states.

**Comment by rstp-god** [comment]
@Drafteed Ty! This just really help me out!
