### ISSUE TITLE
Wrap/Skew Image

### ISSUE THREAD

**Issue by siMobin** [Cuberto/mouse-follower#25]
How I wrap image like this using data attribute?

![image](https://user-images.githubusercontent.com/102217786/222419799-0eb1a220-120c-40fa-a720-d1ed2b73db2d.png)

**Comment by Drafteed** [comment]
> How I wrap image like this using data attribute?

This effect is not related to this project. 
Try searching here: https://tympanus.net/codrops/?s=distortion&search-type=posts

**Comment by siMobin** [comment]
I found it on this repo... then why isn't relevant?
![image](https://user-images.githubusercontent.com/102217786/222523975-b6e11550-a5d0-4b95-ab42-1aa85d6738ae.png)
