### ISSUE TITLE
Doesn't work cursor with Smooth Scrollbar

### ISSUE THREAD

**Issue by HasanSibakhi** [Cuberto/mouse-follower#3]
When using the Smooth Scrollbar the Cursor is not working well, is there any tips on that?

https://github.com/idiotWu/smooth-scrollbar

Thank you,

**Comment by Drafteed** [comment]
Cursor works fine with this library. See https://cuberto.com/ or https://www.sendpotion.com/

**Comment by HasanSibakhi** [comment]
Thank you, I solved the issue
