### ISSUE TITLE
Webflow - SCSS seems to overwrite opacity and size of buttons

### ISSUE THREAD

**Issue by 0dinsama** [Cuberto/mouse-follower#34]
Hey guys, I think I did something wrong when implementing this library on my Webflow Website.

It seems like the styles given in the SCSS file are overwriting some of the changes I'm making such as size and opacity.

Here's the dev web adress if you wan't to take a look : [https://ux-forge.webflow.io/home-v2](url)

I know there's something to do with states but I seem to get my head around it.

Thanks in advance !

Here's the current CSS `.mf-cursor { 
  @media screen and (max-width: 769px) {
    display: none;
  }
  color : #050505;
}
.-cursor-hover {
	font-weight : 500;
	letter-spacing: 1px;
  opacity: 1;
	color : #F44708FF;
}`

And the script : `<script>
const cursor = new MouseFollower({
    container: document.body,  
    speed: 0.8,
    skewing: 1,
    skewingText: 3,
    skewingDelta: 0.001,
    skewingDeltaMax: 0.15,
});
</script>`

**Comment by Drafteed** [comment]
Just copy the scss into your project and change it as you like. The default Mouse Follower SCSS is just an example.
