### ISSUE TITLE
Attention: Reference NANA no longer points to the original page

### ISSUE THREAD

**Issue by lucastrahlendorff** [Cuberto/mouse-follower#36]
The link https://nana-asia.com/ (open with caution) in the reference to NANA in the file [README.MD](https://github.com/Cuberto/mouse-follower/blob/dev/README.MD?plain=1#L456) no longer seems to point to the original page. I was redirected to dubious websites several times. Can somebody confirm this?

**Comment by Drafteed** [comment]
Removed in e22e9ff208ac6e95e47c6af300f0a2e0db8451c2
Thanks 👍
