### ISSUE TITLE
State detection documentation example error

### ISSUE THREAD

**Issue by Giuseppetm** [Cuberto/mouse-follower#6]
Hello,

[here](https://github.com/Cuberto/mouse-follower#state-detection) you can find a little error in the readme about state detection.
The classes name should be `my-image` and `my-input` (not `mf`-image and `mf-input`).

![image](https://user-images.githubusercontent.com/52317197/171407440-332f1617-c11b-4f82-a8ff-87a201d1952f.png)

**Comment by Drafteed** [comment]
Nice catch! Thanks! Fixed in `dev`.
